#!/bin/sh

##  Defaults

ACT=scan
IFCONFIG=/sbin/ifconfig
ROUTE=/sbin/route

usage() {
	cat <<EOF
Usage:
  $0 [scan]
      Scan available networks
  $0 disconnect
      Flush routes and reset interface configuration
  $0 connect NWID
      Connect to a wireless network
  $0 add NWID [OPTION ...]
      Register options for wireless network
  $0 rm  NWID
      Unregister options for wireless network

Configuration files :
  /etc/wifi.conf
  \$HOME/.config/wifi.conf

Variables :
  WIF  wireless interface name
EOF
	exit 1
} >&2

##  Config

config() {
	if [ -f "$1" ]; then
		. "$1"
	fi
}
config /etc/wifi.conf
config "$HOME"/.config/wifi.conf

if ! ifconfig "$WIF" >/dev/null 2>&1; then
    ifconfig "$WIF"
    usage
fi

##  Arguments

if [ $# -gt 0 ]; then
	ACT=$1
	shift
fi

##  Actions

scan() {
	"$IFCONFIG" "$WIF" scan | grep nwid | grep -v 'ieee80211: nwid '
}

disconnect() {
	"$ROUTE" -n flush -iface "$WIF"
	"$IFCONFIG" "$WIF" -bssid -chan -nwflag -nwid -nwkey -wpa -wpakey 0.0.0.0 down
}

connect() {
    echo "Not implemented" >&2
    exit 42
}

add() {
    echo "Not implemented" >&2
    exit 42
}

rm() {
    echo "Not implemented" >&2
    exit 42
}

case "$ACT" in
	s|scan)		scan;;
	d|disconnect)	disconnect;;
	c|connect)	connect "$@";;
	a|add)		add "$@";;
	r|rm)		rm "$@";;
	*)		usage;;
esac
